#!/bin/sh
set -eu

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

printf '%s\n' '[pre-push] go test ./...'
go test ./...

printf '%s\n' '[pre-push] go vet ./...'
go vet ./...

if [ "${SANDBOX_E2E:-0}" = "1" ]; then
  printf '%s\n' '[pre-push] SANDBOX_E2E=1 go test -tags=integration ./...'
  SANDBOX_E2E=1 go test -tags=integration ./...
fi

printf '%s\n' '[pre-push] checks passed'
